package com.example.backend.Enums;

public enum BotState {
    START,
    ENTER_CLIENT_NAME, ENTER_CLIENT_PHONE, CONFIRM_PHONE, SELECT_CUSTOM_CATEGORY, SELECT_TERRITORY, ENTER_CLIENT_ADDRESS, ENTER_CLIENT_LOCATION, ENTER_CLIENT_INN, CONFIRM_LOCATION, SELECT_MENU
}
